In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('qoute_dataset.csv')

In [6]:
quotes = df['quote']

In [7]:
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [8]:
quotes = quotes.str.lower()

In [9]:
import string
translator = str.maketrans('','',string.punctuation)
quotes = quotes.apply(lambda x: x.translate(translator))

In [10]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [11]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [12]:
vocab_size = 10000

tokinizer = Tokenizer(num_words = vocab_size)
tokinizer.fit_on_texts(quotes)

In [13]:
word_index = tokinizer.word_index
print(len(word_index))
list(word_index.items())[:20]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10),
 ('in', 11),
 ('be', 12),
 ('not', 13),
 ('are', 14),
 ('your', 15),
 ('have', 16),
 ('for', 17),
 ('but', 18),
 ('we', 19),
 ('if', 20)]

In [14]:
sequence = tokinizer.texts_to_sequences(quotes)

In [15]:
for i in range(3):
    print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”

In [16]:
for i in range(3):
    print(sequence[i])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

In [17]:
x = []
y =[]

for seq in sequence:
    for i in range(1,len(seq)):
        input_seq = seq[:i]
        output_seq = seq[i]
        x.append(input_seq)
        y.append(output_seq)

In [18]:
len(x)

85271

In [20]:
max_len = max(len(x) for x in x)
print(max_len)

745

In [21]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(x, maxlen=max_len, padding='pre')

In [22]:
y = np.array(y)

In [23]:
X_padded.shape

(85271, 745)

In [24]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y, num_classes=vocab_size)

In [25]:
y.shape

(85271,)

In [26]:
y_one_hot.shape

(85271, 10000)

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,LSTM, Dense

In [28]:
embedding_dim = 50
rnn_units = 128

In [29]:
rnn_model = Sequential()

rnn_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size, activation='softmax'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [30]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [31]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [32]:
lstm_model = Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size, activation='softmax'))

In [33]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [34]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
epochs = 10
batch_size = 128

In [37]:
history_rnn = rnn_model.fit(
    X_padded, y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.1

)

Epoch 1/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 52s 77ms/step - accuracy: 0.0437 - loss: 6.7474 - val_accuracy: 0.0537 - val_loss: 6.5617
Epoch 2/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.0573 - loss: 6.8220 - val_accuracy: 0.0643 - val_loss: 6.7685
Epoch 3/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.0754 - loss: 6.2998 - val_accuracy: 0.0802 - val_loss: 6.5805
Epoch 4/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.0901 - loss: 6.0724 - val_accuracy: 0.0888 - val_loss: 6.5436
Epoch 5/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.0981 - loss: 5.9151 - val_accuracy: 0.0966 - val_loss: 6.5132
Epoch 6/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.1065 - loss: 5.7849 - val_accuracy: 0.0987 - val_loss: 6.5165
Epoch 7/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.1148 - loss: 5.6579 - val_accuracy: 0.0983 - val_loss: 6.5347
Epoch 8/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.1221 - loss: 5.5466 - val_accuracy: 0.1031 - val_loss: 6.4896
Epoch 9/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.1235 - loss: 5.5494 - val_accuracy: 0.1023 - val_loss: 6.4719
Epoch 10/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.1329 - loss: 5.3775 - val_accuracy: 0.1046 - val_loss: 6.4285

In [38]:
epochs = 100
batch_size = 128
history_lstm = lstm_model.fit(
    X_padded, y_one_hot,
    epochs=epochs,
    batch_size= batch_size,
    validation_split=0.1
)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.0387 - loss: 6.7584 - val_accuracy: 0.0432 - val_loss: 6.6783
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.0574 - loss: 6.3244 - val_accuracy: 0.0659 - val_loss: 6.5406
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.0809 - loss: 6.0509 - val_accuracy: 0.0899 - val_loss: 6.4626
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.0981 - loss: 5.8265 - val_accuracy: 0.0955 - val_loss: 6.4382
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1086 - loss: 5.6425 - val_accuracy: 0.0970 - val_loss: 6.4237
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1192 - loss: 5.4700 - val_accuracy: 0.1062 - val_loss: 6.4266
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1289 - loss: 5.3094 - val_accuracy: 0.1080 - val_loss: 6.4490
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1379 - loss: 5.1600 - val_accuracy: 0.1110 - val_loss: 6.4679
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1461 - loss: 5.0185 - val_accuracy: 0.1112 - val_loss: 6.5011
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1524 - loss: 4.8832 - val_accuracy: 0.1125 - val_loss: 6.5568
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1599 - loss: 4.7506 - val_accuracy: 0.1141 - val_loss: 6.6102
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1673 - loss: 4.6206 - val_accuracy: 0.1127 - val_loss: 6.6702
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1774 - loss: 4.4925 - val_accuracy: 0.1135 - val_loss: 6.7317
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1865 - loss: 4.3686 - val_accuracy: 0.1153 - val_loss: 6.7956
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1985 - loss: 4.2470 - val_accuracy: 0.1113 - val_loss: 6.8672
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2122 - loss: 4.1309 - val_accuracy: 0.1130 - val_loss: 6.9453
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2260 - loss: 4.0188 - val_accuracy: 0.1123 - val_loss: 7.0188
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2402 - loss: 3.9122 - val_accuracy: 0.1086 - val_loss: 7.0866
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2550 - loss: 3.8102 - val_accuracy: 0.1080 - val_loss: 7.1843
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2695 - loss: 3.7156 - val_accuracy: 0.1088 - val_loss: 7.2556
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2831 - loss: 3.6264 - val_accuracy: 0.1062 - val_loss: 7.3477
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2950 - loss: 3.5436 - val_accuracy: 0.1072 - val_loss: 7.4134
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3080 - loss: 3.4636 - val_accuracy: 0.1033 - val_loss: 7.5082
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3185 - loss: 3.3900 - val_accuracy: 0.1074 - val_loss: 7.5623
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3297 - loss: 3.3179 - val_accuracy: 0.1032 - val_loss: 7.6513
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 54ms/step - accuracy: 0.3414 - loss: 3.2522 - val_accuracy: 0.1053 - val_loss: 7.7134
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3522 - loss: 3.1856 - val_accuracy: 0.1024 - val_loss: 7.7999
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.3629 - loss: 3.1235 - val_accuracy: 0.1003 - val_loss: 7.8657
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3708 - loss: 3.0645 - val_accuracy: 0.1004 - val_loss: 7.9422
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3821 - loss: 3.0066 - val_accuracy: 0.1000 - val_loss: 8.0066
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3920 - loss: 2.9506 - val_accuracy: 0.0998 - val_loss: 8.0636
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4006 - loss: 2.8974 - val_accuracy: 0.0980 - val_loss: 8.1386
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4099 - loss: 2.8467 - val_accuracy: 0.1001 - val_loss: 8.2008
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4191 - loss: 2.7946 - val_accuracy: 0.0979 - val_loss: 8.2789
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 43s 56ms/step - accuracy: 0.4269 - loss: 2.7462 - val_accuracy: 0.0974 - val_loss: 8.3429
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.4352 - loss: 2.6984 - val_accuracy: 0.0973 - val_loss: 8.4013
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4436 - loss: 2.6538 - val_accuracy: 0.0992 - val_loss: 8.4441
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4529 - loss: 2.6076 - val_accuracy: 0.0976 - val_loss: 8.5159
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4589 - loss: 2.5650 - val_accuracy: 0.0973 - val_loss: 8.5972
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4673 - loss: 2.5210 - val_accuracy: 0.0949 - val_loss: 8.6543
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4747 - loss: 2.4808 - val_accuracy: 0.0919 - val_loss: 8.7030
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4814 - loss: 2.4409 - val_accuracy: 0.0946 - val_loss: 8.7735
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4897 - loss: 2.4023 - val_accuracy: 0.0939 - val_loss: 8.8241
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4972 - loss: 2.3641 - val_accuracy: 0.0931 - val_loss: 8.8941
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5032 - loss: 2.3275 - val_accuracy: 0.0928 - val_loss: 8.9532
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5117 - loss: 2.2918 - val_accuracy: 0.0919 - val_loss: 9.0073
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5176 - loss: 2.2572 - val_accuracy: 0.0928 - val_loss: 9.0610
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5240 - loss: 2.2212 - val_accuracy: 0.0943 - val_loss: 9.1043
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5305 - loss: 2.1887 - val_accuracy: 0.0926 - val_loss: 9.1765
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5365 - loss: 2.1552 - val_accuracy: 0.0911 - val_loss: 9.2302
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5440 - loss: 2.1244 - val_accuracy: 0.0888 - val_loss: 9.3035
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5496 - loss: 2.0923 - val_accuracy: 0.0891 - val_loss: 9.3533
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5543 - loss: 2.0634 - val_accuracy: 0.0895 - val_loss: 9.4012
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5606 - loss: 2.0322 - val_accuracy: 0.0892 - val_loss: 9.4535
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5656 - loss: 2.0050 - val_accuracy: 0.0885 - val_loss: 9.5155
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5726 - loss: 1.9767 - val_accuracy: 0.0886 - val_loss: 9.5802
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5783 - loss: 1.9487 - val_accuracy: 0.0892 - val_loss: 9.6291
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5841 - loss: 1.9229 - val_accuracy: 0.0881 - val_loss: 9.6860
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5886 - loss: 1.8942 - val_accuracy: 0.0876 - val_loss: 9.7445
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5941 - loss: 1.8687 - val_accuracy: 0.0838 - val_loss: 9.7992
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5982 - loss: 1.8449 - val_accuracy: 0.0879 - val_loss: 9.8346
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6038 - loss: 1.8202 - val_accuracy: 0.0856 - val_loss: 9.9216
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6090 - loss: 1.7947 - val_accuracy: 0.0863 - val_loss: 9.9504
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6137 - loss: 1.7710 - val_accuracy: 0.0857 - val_loss: 10.0221
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6194 - loss: 1.7483 - val_accuracy: 0.0854 - val_loss: 10.0729
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6231 - loss: 1.7252 - val_accuracy: 0.0862 - val_loss: 10.1092
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6274 - loss: 1.7037 - val_accuracy: 0.0836 - val_loss: 10.1658
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6321 - loss: 1.6820 - val_accuracy: 0.0835 - val_loss: 10.2241
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6365 - loss: 1.6601 - val_accuracy: 0.0854 - val_loss: 10.2549
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6415 - loss: 1.6398 - val_accuracy: 0.0835 - val_loss: 10.3346
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6441 - loss: 1.6199 - val_accuracy: 0.0845 - val_loss: 10.3858
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6490 - loss: 1.5998 - val_accuracy: 0.0845 - val_loss: 10.4368
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6532 - loss: 1.5799 - val_accuracy: 0.0827 - val_loss: 10.4966
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6575 - loss: 1.5590 - val_accuracy: 0.0847 - val_loss: 10.5457
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.6615 - loss: 1.5422 - val_accuracy: 0.0842 - val_loss: 10.5930
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6659 - loss: 1.5230 - val_accuracy: 0.0816 - val_loss: 10.6620
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6694 - loss: 1.5048 - val_accuracy: 0.0831 - val_loss: 10.6835
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6727 - loss: 1.4883 - val_accuracy: 0.0800 - val_loss: 10.7426
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6752 - loss: 1.4705 - val_accuracy: 0.0844 - val_loss: 10.7948
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6808 - loss: 1.4526 - val_accuracy: 0.0807 - val_loss: 10.8444
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6839 - loss: 1.4364 - val_accuracy: 0.0813 - val_loss: 10.8843
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6866 - loss: 1.4212 - val_accuracy: 0.0811 - val_loss: 10.9339
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6910 - loss: 1.4046 - val_accuracy: 0.0826 - val_loss: 10.9803
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6951 - loss: 1.3881 - val_accuracy: 0.0810 - val_loss: 11.0409
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6982 - loss: 1.3733 - val_accuracy: 0.0810 - val_loss: 11.0985
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7001 - loss: 1.3578 - val_accuracy: 0.0804 - val_loss: 11.1277
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7039 - loss: 1.3427 - val_accuracy: 0.0813 - val_loss: 11.1821
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7081 - loss: 1.3266 - val_accuracy: 0.0799 - val_loss: 11.2256
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7106 - loss: 1.3139 - val_accuracy: 0.0795 - val_loss: 11.2727
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7138 - loss: 1.3012 - val_accuracy: 0.0784 - val_loss: 11.3308
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7161 - loss: 1.2851 - val_accuracy: 0.0790 - val_loss: 11.3857
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7183 - loss: 1.2725 - val_accuracy: 0.0782 - val_loss: 11.4194
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7214 - loss: 1.2590 - val_accuracy: 0.0783 - val_loss: 11.4632
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7256 - loss: 1.2436 - val_accuracy: 0.0793 - val_loss: 11.5190
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7287 - loss: 1.2323 - val_accuracy: 0.0772 - val_loss: 11.5392
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7304 - loss: 1.2186 - val_accuracy: 0.0774 - val_loss: 11.6069
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7341 - loss: 1.2059 - val_accuracy: 0.0780 - val_loss: 11.6539
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7364 - loss: 1.1942 - val_accuracy: 0.0760 - val_loss: 11.7100
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7381 - loss: 1.1824 - val_accuracy: 0.0766 - val_loss: 11.7391
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7417 - loss: 1.1696 - val_accuracy: 0.0775 - val_loss: 11.8022

In [39]:
from tensorflow.keras.models import load_model

In [42]:
lstm_model = load_model("lstm_model.h5")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [41]:
lstm_model.save("lstm_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [44]:
index_to_word ={}
for word,index in word_index.items():
  index_to_word[index] = word

In [45]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [53]:
def predictor(model,tokenizer,text,max_len):
  text = text.lower()

  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')

  pred = model.predict(seq,verbose = 0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [54]:
seed_text = "what are you"
next_word = predictor(lstm_model,tokinizer,seed_text,max_len)
print(next_word)

going

In [55]:
def generate_text(model,tokenizer,seed_text,max_len,n_words):
  for _ in range(n_words):
    next_word = predictor(model,tokenizer,seed_text,max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

In [56]:
seed = 'are you a'
generate_text = generate_text(lstm_model,tokinizer,seed,max_len,10)
print(generate_text)

are you a great and if you are going to try to make

In [57]:
import pickle
with open("tokenizer.pkl", "wb") as f:
  pickle.dump(tokinizer, f)

In [58]:
with open("max_len.pkl", "wb") as f:
  pickle.dump(max_len, f)